[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

board_build.partitions = huge_app.csv

lib_deps =
    lvgl/lvgl @ ^8.3.9
    bodmer/TFT_eSPI @ ^2.5.31

build_flags =
    -D USER_SETUP_LOADED=1
    -D GC9A01_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=4
    -D TOUCH_CS=-1 ; Disable touch to suppress warning
    -D SPI_FREQUENCY=80000000 ; Overclocking screen interface for smooth 60FPS fluid animations!
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D LV_CONF_SKIP=1
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=0 ; Disabled here: Byte swapping is handled efficiently via software in main.cpp, not by the LVGL library.
    -D LV_TICK_CUSTOM=1
    -D LV_FONT_MONTSERRAT_12=1
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_20=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_MONTSERRAT_40=1
    -O2