// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_uiImgGaugeBg = NULL;
lv_obj_t * ui_uiArcMain = NULL;
lv_obj_t * ui_uiLbl18 = NULL;
lv_obj_t * ui_uiLbl16 = NULL;
lv_obj_t * ui_uiLbl14 = NULL;
lv_obj_t * ui_uiLbl12 = NULL;
lv_obj_t * ui_uiLbl10 = NULL;
lv_obj_t * ui_uiLbl8 = NULL;
lv_obj_t * ui_uiBatteryImg = NULL;
lv_obj_t * ui_uiTempimg = NULL;
lv_obj_t * ui_uiTemplevel = NULL;
lv_obj_t * ui_uiGas = NULL;
lv_obj_t * ui_uiGaslevel = NULL;
lv_obj_t * ui_ImgNeedleBlue = NULL;
lv_obj_t * ui_ImgNeedleGreen = NULL;
lv_obj_t * ui_ImgNeedleRed = NULL;
lv_obj_t * ui_ImgHubBlue = NULL;
lv_obj_t * ui_ImgHubGreen = NULL;
lv_obj_t * ui_ImgHubRed = NULL;
lv_obj_t * ui_LblValue = NULL;
lv_obj_t * ui_LblUnit = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiImgGaugeBg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_uiImgGaugeBg, &ui_img_gauge_bg_png);
    lv_obj_set_width(ui_uiImgGaugeBg, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_uiImgGaugeBg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_uiImgGaugeBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImgGaugeBg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiImgGaugeBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiArcMain = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_uiArcMain, 220);
    lv_obj_set_height(ui_uiArcMain, 220);
    lv_obj_set_align(ui_uiArcMain, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_uiArcMain, 50);
    lv_obj_set_style_arc_color(ui_uiArcMain, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_uiArcMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_uiArcMain, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_uiArcMain, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_uiArcMain, lv_color_hex(0x00CCFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_uiArcMain, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_uiArcMain, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_uiArcMain, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_uiArcMain, lv_color_hex(0x00CCFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_uiArcMain, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_uiArcMain, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_uiArcMain, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_uiArcMain, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiArcMain, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_uiLbl18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLbl18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLbl18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLbl18, 51);
    lv_obj_set_y(ui_uiLbl18, 53);
    lv_obj_set_align(ui_uiLbl18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLbl18, "18");
    lv_obj_set_style_text_color(ui_uiLbl18, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLbl18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLbl18, &ui_font_Chakra20Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLbl16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLbl16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLbl16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLbl16, 72);
    lv_obj_set_y(ui_uiLbl16, -11);
    lv_obj_set_align(ui_uiLbl16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLbl16, "16");
    lv_obj_set_style_text_color(ui_uiLbl16, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLbl16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLbl16, &ui_font_Chakra20Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLbl14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLbl14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLbl14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLbl14, 34);
    lv_obj_set_y(ui_uiLbl14, -65);
    lv_obj_set_align(ui_uiLbl14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLbl14, "14");
    lv_obj_set_style_text_color(ui_uiLbl14, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLbl14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLbl14, &ui_font_Chakra20Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLbl12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLbl12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLbl12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLbl12, -33);
    lv_obj_set_y(ui_uiLbl12, -66);
    lv_obj_set_align(ui_uiLbl12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLbl12, "12");
    lv_obj_set_style_text_color(ui_uiLbl12, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLbl12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLbl12, &ui_font_Chakra20Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLbl10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLbl10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLbl10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLbl10, -72);
    lv_obj_set_y(ui_uiLbl10, -13);
    lv_obj_set_align(ui_uiLbl10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLbl10, "10");
    lv_obj_set_style_text_color(ui_uiLbl10, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLbl10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLbl10, &ui_font_Chakra20Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLbl8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLbl8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLbl8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLbl8, -53);
    lv_obj_set_y(ui_uiLbl8, 51);
    lv_obj_set_align(ui_uiLbl8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLbl8, "8");
    lv_obj_set_style_text_color(ui_uiLbl8, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLbl8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLbl8, &ui_font_Chakra20Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiBatteryImg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_uiBatteryImg, &ui_img_car_batter_png);
    lv_obj_set_width(ui_uiBatteryImg, LV_SIZE_CONTENT);   /// 46
    lv_obj_set_height(ui_uiBatteryImg, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_uiBatteryImg, 0);
    lv_obj_set_y(ui_uiBatteryImg, 55);
    lv_obj_set_align(ui_uiBatteryImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiBatteryImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiBatteryImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_uiBatteryImg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_uiBatteryImg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiTempimg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_uiTempimg, &ui_img_temp_png);
    lv_obj_set_width(ui_uiTempimg, LV_SIZE_CONTENT);   /// 46
    lv_obj_set_height(ui_uiTempimg, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_uiTempimg, 51);
    lv_obj_set_y(ui_uiTempimg, 82);
    lv_obj_set_align(ui_uiTempimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiTempimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiTempimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_uiTempimg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_uiTempimg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiTemplevel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiTemplevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiTemplevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiTemplevel, 22);
    lv_obj_set_y(ui_uiTemplevel, 84);
    lv_obj_set_align(ui_uiTemplevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiTemplevel, "00");
    lv_obj_set_style_text_color(ui_uiTemplevel, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiTemplevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiTemplevel, &ui_font_ChakraPetchBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiGas = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_uiGas, &ui_img_gas_png);
    lv_obj_set_width(ui_uiGas, LV_SIZE_CONTENT);   /// 46
    lv_obj_set_height(ui_uiGas, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_uiGas, -51);
    lv_obj_set_y(ui_uiGas, 82);
    lv_obj_set_align(ui_uiGas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiGas, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiGas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_uiGas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_uiGas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiGaslevel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiGaslevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiGaslevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiGaslevel, -22);
    lv_obj_set_y(ui_uiGaslevel, 84);
    lv_obj_set_align(ui_uiGaslevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiGaslevel, "00");
    lv_obj_set_style_text_color(ui_uiGaslevel, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiGaslevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiGaslevel, &ui_font_ChakraPetchBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgNeedleBlue = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgNeedleBlue, &ui_img_needle_blue_png);
    lv_obj_set_width(ui_ImgNeedleBlue, LV_SIZE_CONTENT);   /// 115
    lv_obj_set_height(ui_ImgNeedleBlue, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImgNeedleBlue, 52);
    lv_obj_set_y(ui_ImgNeedleBlue, 0);
    lv_obj_set_align(ui_ImgNeedleBlue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgNeedleBlue, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgNeedleBlue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImgNeedleBlue, 5, 8);
    lv_img_set_angle(ui_ImgNeedleBlue, 2400);

    ui_ImgNeedleGreen = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgNeedleGreen, &ui_img_needle_green_png);
    lv_obj_set_width(ui_ImgNeedleGreen, LV_SIZE_CONTENT);   /// 115
    lv_obj_set_height(ui_ImgNeedleGreen, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImgNeedleGreen, 52);
    lv_obj_set_y(ui_ImgNeedleGreen, 0);
    lv_obj_set_align(ui_ImgNeedleGreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgNeedleGreen, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgNeedleGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImgNeedleGreen, 5, 8);
    lv_img_set_angle(ui_ImgNeedleGreen, 3200);

    ui_ImgNeedleRed = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgNeedleRed, &ui_img_needle_red_png);
    lv_obj_set_width(ui_ImgNeedleRed, LV_SIZE_CONTENT);   /// 115
    lv_obj_set_height(ui_ImgNeedleRed, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImgNeedleRed, 52);
    lv_obj_set_y(ui_ImgNeedleRed, 0);
    lv_obj_set_align(ui_ImgNeedleRed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgNeedleRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgNeedleRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImgNeedleRed, 5, 8);
    lv_img_set_angle(ui_ImgNeedleRed, 450);

    ui_ImgHubBlue = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgHubBlue, &ui_img_hub_b_png);
    lv_obj_set_width(ui_ImgHubBlue, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_ImgHubBlue, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_ImgHubBlue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHubBlue, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHubBlue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgHubGreen = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgHubGreen, &ui_img_hub_g_png);
    lv_obj_set_width(ui_ImgHubGreen, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_ImgHubGreen, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_ImgHubGreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHubGreen, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHubGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgHubRed = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgHubRed, &ui_img_hub_r_png);
    lv_obj_set_width(ui_ImgHubRed, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_ImgHubRed, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_ImgHubRed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHubRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHubRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblValue, -1);
    lv_obj_set_y(ui_LblValue, -1);
    lv_obj_set_align(ui_LblValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblValue, "12.4");
    lv_obj_set_style_text_font(ui_LblValue, &ui_font_ChakraPetchBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblUnit = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblUnit, 0);
    lv_obj_set_y(ui_LblUnit, 16);
    lv_obj_set_align(ui_LblUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblUnit, "VOLTS");
    lv_obj_set_style_text_font(ui_LblUnit, &ui_font_ChakraPetchBold10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_uiImgGaugeBg = NULL;
    ui_uiArcMain = NULL;
    ui_uiLbl18 = NULL;
    ui_uiLbl16 = NULL;
    ui_uiLbl14 = NULL;
    ui_uiLbl12 = NULL;
    ui_uiLbl10 = NULL;
    ui_uiLbl8 = NULL;
    ui_uiBatteryImg = NULL;
    ui_uiTempimg = NULL;
    ui_uiTemplevel = NULL;
    ui_uiGas = NULL;
    ui_uiGaslevel = NULL;
    ui_ImgNeedleBlue = NULL;
    ui_ImgNeedleGreen = NULL;
    ui_ImgNeedleRed = NULL;
    ui_ImgHubBlue = NULL;
    ui_ImgHubGreen = NULL;
    ui_ImgHubRed = NULL;
    ui_LblValue = NULL;
    ui_LblUnit = NULL;

}
