// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_uiImgGaugeBg;
extern lv_obj_t * ui_uiArcMain;
extern lv_obj_t * ui_uiLbl18;
extern lv_obj_t * ui_uiLbl16;
extern lv_obj_t * ui_uiLbl14;
extern lv_obj_t * ui_uiLbl12;
extern lv_obj_t * ui_uiLbl10;
extern lv_obj_t * ui_uiLbl8;
extern lv_obj_t * ui_uiBatteryImg;
extern lv_obj_t * ui_uiTempimg;
extern lv_obj_t * ui_uiTemplevel;
extern lv_obj_t * ui_uiGas;
extern lv_obj_t * ui_uiGaslevel;
extern lv_obj_t * ui_ImgNeedleBlue;
extern lv_obj_t * ui_ImgNeedleGreen;
extern lv_obj_t * ui_ImgNeedleRed;
extern lv_obj_t * ui_ImgHubBlue;
extern lv_obj_t * ui_ImgHubGreen;
extern lv_obj_t * ui_ImgHubRed;
extern lv_obj_t * ui_LblValue;
extern lv_obj_t * ui_LblUnit;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

