// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_gauge_bg_png);    // assets/Gauge_bg.png
LV_IMG_DECLARE(ui_img_car_batter_png);    // assets/car_batter.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/Temp.png
LV_IMG_DECLARE(ui_img_gas_png);    // assets/Gas.png
LV_IMG_DECLARE(ui_img_needle_blue_png);    // assets/needle_blue.png
LV_IMG_DECLARE(ui_img_needle_green_png);    // assets/needle_green.png
LV_IMG_DECLARE(ui_img_needle_red_png);    // assets/needle_red.png
LV_IMG_DECLARE(ui_img_hub_b_png);    // assets/hub_b.png
LV_IMG_DECLARE(ui_img_hub_g_png);    // assets/Hub_g.png
LV_IMG_DECLARE(ui_img_hub_r_png);    // assets/hub_r.png

// FONTS
LV_FONT_DECLARE(ui_font_Chakra20Bold);
LV_FONT_DECLARE(ui_font_ChakraPetchBold10);
LV_FONT_DECLARE(ui_font_ChakraPetchBold18);
LV_FONT_DECLARE(ui_font_ChakraPetchBold22);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
